version: '3.8'

services:
  postgres:
    container_name: kokodi-postgres
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: gamedb
      POSTGRES_USER: root
      POSTGRES_PASSWORD: pass

    restart: no