spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/gamedb
    driver-class-name: org.postgresql.Driver
    username: root
    password: pass

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect
    defer-datasource-initialization: true
  sql:
    init:
      mode: always

  security:
    jwt:
      time: 10800000
